// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Madflight_Configurator

#ifndef _MADFLIGHT_CONFIGURATOR_UI_H
#define _MADFLIGHT_CONFIGURATOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Madflight_Configurator.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_config_40x40_png);    // assets/config_40x40.png
LV_IMG_DECLARE(ui_img_imu_40x40_png);    // assets/imu_40x40.png
LV_IMG_DECLARE(ui_img_monitor_40x40_png);    // assets/monitor_40x40.png
LV_IMG_DECLARE(ui_img_motor_40x40_png);    // assets/motor_40x40.png
LV_IMG_DECLARE(ui_img_save_40x40_png);    // assets/save_40x40.png
LV_IMG_DECLARE(ui_img_cancel_40x40_png);    // assets/cancel_40x40.png
LV_IMG_DECLARE(ui_img_scisky_240x116_png);    // assets/scisky_240x116.png
LV_IMG_DECLARE(ui_img_scisky_320x240_png);    // assets/scisky_320x240.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
