// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Madflight_Configurator

#include "ui.h"

void loadConfig(lv_event_t * e)
{
	lv_textarea_add_text(ui_Console, "Load Config\n");
}

void calibrate(lv_event_t * e)
{
	lv_textarea_add_text(ui_Console, "Calibrate\n");
}

void doMonitoring(lv_event_t * e)
{
	lv_textarea_add_text(ui_Console, "Monitoring\n");
}

void spinMotor(lv_event_t * e)
{
	lv_textarea_add_text(ui_Console, "Spin motors\n");
}

void saveConfig(lv_event_t * e)
{
	lv_textarea_add_text(ui_Console, "Save\n");
}

void discardChanges(lv_event_t * e)
{
	lv_textarea_add_text(ui_Console, "Cancel\n");
}
