// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Madflight_Configurator

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void loadConfig(lv_event_t * e);
void calibrate(lv_event_t * e);
void doMonitoring(lv_event_t * e);
void spinMotor(lv_event_t * e);
void saveConfig(lv_event_t * e);
void discardChanges(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
