// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Madflight_Configurator

#include "ui.h"

lv_obj_t * ui_Madflight_Configurator = NULL;
lv_obj_t * ui_Root = NULL;
lv_obj_t * ui_Command_Panel = NULL;
lv_obj_t * ui_Config = NULL;
lv_obj_t * ui_IMU = NULL;
lv_obj_t * ui_Monitor = NULL;
lv_obj_t * ui_Motor = NULL;
lv_obj_t * ui_Save = NULL;
lv_obj_t * ui_Discard = NULL;
lv_obj_t * ui_Console = NULL;
// event funtions
void ui_event_Config(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        loadConfig(e);
    }
}

void ui_event_IMU(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        calibrate(e);
    }
}

void ui_event_Monitor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        doMonitoring(e);
    }
}

void ui_event_Motor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        spinMotor(e);
    }
}

void ui_event_Save(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveConfig(e);
    }
}

void ui_event_Discard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        discardChanges(e);
    }
}

// build funtions

void ui_Madflight_Configurator_screen_init(void)
{
    ui_Madflight_Configurator = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Madflight_Configurator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Madflight_Configurator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Madflight_Configurator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Root = lv_obj_create(ui_Madflight_Configurator);
    lv_obj_remove_style_all(ui_Root);
    lv_obj_set_width(ui_Root, 300);
    lv_obj_set_height(ui_Root, 234);
    lv_obj_set_x(ui_Root, 0);
    lv_obj_set_y(ui_Root, -4);
    lv_obj_set_align(ui_Root, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Root, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Command_Panel = lv_obj_create(ui_Root);
    lv_obj_remove_style_all(ui_Command_Panel);
    lv_obj_set_width(ui_Command_Panel, 295);
    lv_obj_set_height(ui_Command_Panel, 55);
    lv_obj_set_x(ui_Command_Panel, 0);
    lv_obj_set_y(ui_Command_Panel, -80);
    lv_obj_set_align(ui_Command_Panel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Command_Panel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Command_Panel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_remove_flag(ui_Command_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Command_Panel, lv_color_hex(0xAFC3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Command_Panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Command_Panel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Config = lv_button_create(ui_Command_Panel);
    lv_obj_set_width(ui_Config, 40);
    lv_obj_set_height(ui_Config, 40);
    lv_obj_set_align(ui_Config, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Config, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Config, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Config, lv_color_hex(0xB6D3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Config, &ui_img_config_40x40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Config, lv_color_hex(0x111158), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Config, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMU = lv_button_create(ui_Command_Panel);
    lv_obj_set_width(ui_IMU, 40);
    lv_obj_set_height(ui_IMU, 40);
    lv_obj_set_align(ui_IMU, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IMU, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_IMU, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IMU, lv_color_hex(0xB6D3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IMU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_IMU, &ui_img_imu_40x40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_IMU, lv_color_hex(0x111158), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_IMU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Monitor = lv_button_create(ui_Command_Panel);
    lv_obj_set_width(ui_Monitor, 40);
    lv_obj_set_height(ui_Monitor, 40);
    lv_obj_set_align(ui_Monitor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Monitor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Monitor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Monitor, lv_color_hex(0xB6D3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Monitor, &ui_img_monitor_40x40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Monitor, lv_color_hex(0x111158), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Monitor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Motor = lv_button_create(ui_Command_Panel);
    lv_obj_set_width(ui_Motor, 40);
    lv_obj_set_height(ui_Motor, 40);
    lv_obj_set_align(ui_Motor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Motor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Motor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Motor, lv_color_hex(0xB6D3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Motor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Motor, &ui_img_motor_40x40_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Motor, lv_color_hex(0x111158), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Motor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Save = lv_button_create(ui_Command_Panel);
    lv_obj_set_width(ui_Save, 40);
    lv_obj_set_height(ui_Save, 40);
    lv_obj_set_align(ui_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Save, lv_color_hex(0xB6D3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Save, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Save, &ui_img_save_40x40_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Discard = lv_button_create(ui_Command_Panel);
    lv_obj_set_width(ui_Discard, 40);
    lv_obj_set_height(ui_Discard, 40);
    lv_obj_set_align(ui_Discard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Discard, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Discard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Discard, lv_color_hex(0xB6D3FB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Discard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Discard, &ui_img_cancel_40x40_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Console = lv_textarea_create(ui_Root);
    lv_obj_set_width(ui_Console, 294);
    lv_obj_set_height(ui_Console, 164);
    lv_obj_set_x(ui_Console, 1);
    lv_obj_set_y(ui_Console, 35);
    lv_obj_set_align(ui_Console, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Console, "Console...");
    lv_obj_set_style_text_color(ui_Console, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Console, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Console, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Console, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Console, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Console, &ui_img_scisky_240x116_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Console, 85, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Console, lv_color_hex(0x6A8EFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Console, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Console, lv_color_hex(0xAFC3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Console, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Config, ui_event_Config, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IMU, ui_event_IMU, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Monitor, ui_event_Monitor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Motor, ui_event_Motor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Save, ui_event_Save, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Discard, ui_event_Discard, LV_EVENT_ALL, NULL);

}

void ui_Madflight_Configurator_screen_destroy(void)
{
    if(ui_Madflight_Configurator) lv_obj_del(ui_Madflight_Configurator);

    // NULL screen variables
    ui_Madflight_Configurator = NULL;
    ui_Root = NULL;
    ui_Command_Panel = NULL;
    ui_Config = NULL;
    ui_IMU = NULL;
    ui_Monitor = NULL;
    ui_Motor = NULL;
    ui_Save = NULL;
    ui_Discard = NULL;
    ui_Console = NULL;

}
