// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.5
// Project name: Madflight_Configurator

#ifndef UI_MADFLIGHT_CONFIGURATOR_H
#define UI_MADFLIGHT_CONFIGURATOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Madflight_Configurator
extern void ui_Madflight_Configurator_screen_init(void);
extern void ui_Madflight_Configurator_screen_destroy(void);
extern lv_obj_t * ui_Madflight_Configurator;
extern lv_obj_t * ui_Root;
extern lv_obj_t * ui_Command_Panel;
extern void ui_event_Config(lv_event_t * e);
extern lv_obj_t * ui_Config;
extern void ui_event_IMU(lv_event_t * e);
extern lv_obj_t * ui_IMU;
extern void ui_event_Monitor(lv_event_t * e);
extern lv_obj_t * ui_Monitor;
extern void ui_event_Motor(lv_event_t * e);
extern lv_obj_t * ui_Motor;
extern void ui_event_Save(lv_event_t * e);
extern lv_obj_t * ui_Save;
extern void ui_event_Discard(lv_event_t * e);
extern lv_obj_t * ui_Discard;
extern lv_obj_t * ui_Console;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

